# Generated by Django 4.1.5 on 2023-02-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='date_pledged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
